const SET_USER = 'SET_USER';
const SET_IS_AUTH = 'SET_IS_AUTH';

const SET_USERS = 'SET_USERS';
const SET_PAGE = 'SET_PAGE';
const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';

const SET_COLLECTIONS = 'SET_COLLECTIONS';
const SET_ITEMS = 'SET_ITEMS';

export { SET_USER, SET_IS_AUTH, SET_USERS, SET_PAGE, SET_TOTAL_COUNT, SET_COLLECTIONS, SET_ITEMS };
